apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mongo.name }}
  name: {{ .Values.mongo.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: {{ .Values.mongo.name }}