apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.pagerbotAdmin.name }}
  name: {{ .Values.pagerbotAdmin.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 4567
    targetPort: 4567
  selector:
    app: pagerbot-admin