apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.pagerbotAdmin.name }}
  name: {{ .Values.pagerbotAdmin.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.pagerbotAdmin.name }}
    spec:
      containers:
      - args:
        - rerun
        - -b
        - --
        - ruby
        - lib/pagerbot.rb
        - admin
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.pagerbotAdmin.name }}
        ports:
        - containerPort: 4567
        env:
          - name: LOG_LEVEL
            value: "debug"
          - name: MONGODB_URI
            value: "mongodb://mongo:27017/pagerbot"
      restartPolicy: Always