# Default values for pagerbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.s
namespace: pagerbot-ops

mongo:
  name: mongo
  image:
    repository: mongo
    tag: 3
  storageSize: 20Mi

pagerbotAdmin:
  name: pagerbot-admin
  ingressClass: "nginx-public"
  hostname: "pagerbot.ops.eks.lumoslabs.com"

pagerbot:
  name: pagerbot
  deployed: false # Change to true manually after entering keys on localhost:4567 (pagerbot-admin)

image:
  repository: quay.io/lumoslabs/pagerbotv2 #quay.io/lunarway/pagerbot #change to quay.io/lumoslabs/pagerbotv2
  #tag: latest
